# Generated by Django 5.1.7 on 2025-03-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=0, verbose_name='orden'),
        ),
    ]
