# Generated by Django 5.1.7 on 2025-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.IntegerField(default=1, verbose_name='orden'),
        ),
    ]
